version: '3.1'

services:

    db:
        image: mariadb:10.8.3
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: secret123
        ports:
            - "3306:3306"
    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
